# Generated by Django 4.2 on 2023-05-01 14:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reparacionesApp', '0002_alter_reparaciones_repuestos'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='clientes',
            options={'verbose_name_plural': 'clientes'},
        ),
        migrations.AlterModelOptions(
            name='encargos',
            options={'verbose_name_plural': 'encargos'},
        ),
        migrations.AlterModelOptions(
            name='manodeobra',
            options={'ordering': ['orden'], 'verbose_name_plural': 'mano de obra'},
        ),
        migrations.AlterModelOptions(
            name='reparaciones',
            options={'verbose_name_plural': 'reparaciones'},
        ),
        migrations.AlterModelOptions(
            name='repuestos',
            options={'verbose_name_plural': 'repuestos'},
        ),
        migrations.AlterModelOptions(
            name='trabajos',
            options={'verbose_name_plural': 'trabajos'},
        ),
    ]
